[theme]
primaryColor = "#ffffff"
backgroundColor = "#000000"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#ffffff"
base = "dark"

[server]
headless = false
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
